### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by GitHubRalph** [GitHubRalph/stampsadmin#3]
- [x] change width to 150
- [x] Menu for punches
- [x] Menu for stampsset
- [x] Menu for inkpad
- [x] Menu for category
- [x] Menu for type
- [x] Mapping to category
- [x] Mapping to type
- [x] From Settings zu Details with NodePage
- [x] Menu with function
- [x] Search implement

**Comment by GitHubRalph** [comment]
close issue because split in another issue
